name: Publish

on:
  workflow_dispatch:
  push:
   paths-ignore:
     - '.gitignore'
     - 'LICENSE'
     - 'README.md'
     - 'gradle.yml'
     - "pictures/"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build Project
        run: ./gradlew launcher:shadowJar
      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Base
          path: launcher/build/libs/
          if-no-files-found: error
